env:
    CIRRUS_SHELL: bash

task:
  name: "CR Builder CI"
  timeout_in: 300m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Var_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/vars.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/build.sh | bash

  Upload_script:
      - curl https://raw.githubusercontent.com/DevTeady/RBuilder/main/upload.sh | bash
