env:

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "CR Builder CI"
  timeout_in: 300m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/build.sh | bash

  Upload_script:
      - export TIMEOUT=20160 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/DevTeady/RBuilder/main/upload.sh | bash
