env:
    CIRRUS_SHELL: bash

task:
  name: "CR Builder CI (LAGACY)"
  timeout_in: 300m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Build_script:
      - curl -sL https://raw.githubusercontent.com/DevTeady/RBuilder/main/lagacy_build.sh | bash
